name: Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # environment:
    #   name: NUGET_ENV
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .Net SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Publish
        run: cd MongoCRUD && dotnet publish --no-restore -c Release /p:UseAppHost=false
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: /bin/Release/net9.0/publish/**/*
